---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intake(intake)
	coordinator(coordinator)
	scraper(scraper)
	after_scrape(after_scrape)
	chilling(chilling)
	no_results(no_results)
	retry(retry)
	news(news)
	skip_news(skip_news)
	whatsapp(whatsapp)
	evaluator(evaluator)
	seller(seller)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake;
	after_scrape -.-> news;
	after_scrape -.-> skip_news;
	chilling --> coordinator;
	coordinator --> scraper;
	evaluator -.-> retry;
	evaluator -.-> seller;
	intake --> coordinator;
	news --> whatsapp;
	no_results --> seller;
	retry --> coordinator;
	scraper -.-> after_scrape;
	scraper -.-> chilling;
	scraper -.-> no_results;
	skip_news --> whatsapp;
	whatsapp --> evaluator;
	seller --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
